### PR TITLE
Update hnswlib to v0.8.0

### PR DESCRIPTION
**Pull request by cocoa-xu**
This PR updated hnswlib to v0.8.0, and added the following functions:

- [`HNSWLib.BFIndex.get_max_elements/1`](https://github.com/elixir-nx/hnswlib/commit/e2693e1bfbec2a7317c5b1b64da21a4ea3100d91)
- [`HNSWLib.BFIndex.get_current_count/1`](https://github.com/elixir-nx/hnswlib/commit/73d92841683ef3cf1feaaf9e0f330969d502cdae)
- [`HNSWLib.BFIndex.{set_num_threads/2,get_num_threads/1}`](https://github.com/elixir-nx/hnswlib/commit/3b9c04d23bfc4e20874239113c9f4dc673939dec)
- [`HNSWLib.Index.index_file_size/1`](https://github.com/elixir-nx/hnswlib/commit/47d263a0c2bdadd0aea3505c8253a2861866c59f)

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

**Comment by cocoa-xu** [comment]
Restarted Windows CI as it seems stuck for more than half an hour... Not sure about the reason...

**Comment by josevalim** [comment]
Yeah, Windows is still getting stuck for some reason. :(

**Comment by cocoa-xu** [comment]
> Yeah, Windows is still getting stuck for some reason. :(

Yeah... I'll cancel the workflow and try it with latest version of Erlang and Elixir. If it still stuck, I'll try it on a physical machine or later.

**Comment by cocoa-xu** [comment]
Finally I have access to a physical Windows machine. It seems that the problem only occurs when testing `HNSWLib.BFIndex.delete_vector/2`, i.e., `mix test test/hnswlib_bfindex_test.exs:315`

```shell
C:\Users\cocoa\Documents\GitHub\hnswlib>mix test test/hnswlib_index_test.exs
................................................
Finished in 2.3 seconds (0.00s async, 2.3s sync)
48 tests, 0 failures

Randomized with seed 921679

C:\Users\cocoa\Documents\GitHub\hnswlib>mix test test/hnswlib_bfindex_test.exs:315
# crashed
```
hnswlib_bfindex

**Pull request merged**
