### PR TITLE
lower required glibcxx version

### PR DESCRIPTION
**Pull request by cocoa-xu**
Links to #9

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @cocoa-xu! Let's give compiling with 20.04 a try and, if people still run into issue, having this as reference will be very helpful. :)

**Comment by cocoa-xu** [comment]
Yeah I was near there but it seems that we still have some [weird floating-point issues](https://github.com/cocoa-xu/hnswlib/actions/runs/6205316274/job/16848380797#step:5:215) with ppc64le, as well as [some issue with the qemu-aarch64-static emulator](https://github.com/cocoa-xu/hnswlib/actions/runs/6205316274/job/16848380734#step:5:183) that would cause a segementation fault when doing `mix local.hex --force`.

**Review by josevalim — APPROVED** [review]

**Comment by cocoa-xu** [comment]
Hi @josevalim, I decided to only compile x86_64, i686 and s390 on manylinux2014 while keeping the rest of Linux targets compiled on ubuntu-20.04. Doing so should lower the required glibcxx version to 2.14 for x86_64, i686 and s390. 

Moreover, as I believe most users are using x86_64-linux-gnu, lowering the glibcxx version should address the issue for users who have to work with some old versions of Linux.

**Comment by josevalim** [comment]
Sounds good to me, as you prefer!

**Pull request merged**
